export const amenities = [
  "Adequate Seating",
  "Table Space",
  "Projector & Screen",
  "Whiteboard & Markers",
  "Video Conferencing Facilities",
  "On-Site Support Staff",
  "Audio & visual Equipment",
  "Wi-Fi access",
  "Power Outlets",
  "Natural Light",
  "Temperature Control",
  "Flip Charts",
  "Storage Space",
  "Water and Coffee Station",
  "Emergency Exit",
].map((option) => ({
  title: option,
  value: option,
}));
